name: Run rspec
on:
  push:
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        ruby: [ 2.4, 2.5, 2.6 ]
    name: rspec with ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          bundler: 1

      - run: bundle exec rspec